### ISSUE TITLE
Investigate drop in download count associated with macOS

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer_download#30]
> There is a big drop in downloads on macOS, starting from about April 2021 (140 downloads per day) to September 2021 (60 downloads per day). Do you think it is really that much less macOS users downloading Slicer or there is some technical issue? macOS downloads in the US dropped in July 2021 from about 30 to about 13 and stayed at that level – is it a coincidence that downloads with empty version start about the same date? (situation is similar in Western Europe

_Originally reported by @lassoan on Jul 11, 2022 by email_

**Comment by lassoan** [comment]
macOS downloads:

![image](https://user-images.githubusercontent.com/307929/181617045-90b143e8-205e-4ab9-af3d-5aea8263b7bc.png)

Windows+Linux downloads:

![image](https://user-images.githubusercontent.com/307929/181617199-36439763-3114-4277-b9af-ace0bebc3411.png)

**Comment by jamesobutler** [comment]
As of posting this there is definitely a large discrepancy between macOS downloads from slicer-packages.kitware.com and the download stats page. I'm not sure how frequently the download stats page gets updated (maybe once a day?), but would not explain this discrepancy.

Slicer 5.0.2 totals from :
https://slicer-packages.kitware.com/#collection/5f4474d0e1d8c75dfc70547e/folder/6286cc6ee8408647b39f7e46

Slicer 5.0.3 totals from:
https://slicer-packages.kitware.com/#collection/5f4474d0e1d8c75dfc70547e/folder/62cc513eaa08d161a31c1372

Slicer 5.0.x Download Stats Page Total from:
https://download.slicer.org/download-stats/ reported values filtered by OS, Stability: release, Version: 5.0


| OS | Slicer 5.0.2 | Slicer 5.0.3 | Slicer 5.0.x Total | Slicer 5.0.x Download Stats Page Total|
|----|--------------|-------------|-------------------|------------------------------------------|
|Linux|2838|841|3679|3152|
|macOS|4276|1438|5117|1091|
|Windows|21266|3668|24934|23950|

It was discussed at the recent weekly hangout to make the download stats page use the number of times the macOS package was downloaded rather than using the agent of the device used to download a package. You could for example use Windows to download a macOS package and vice versa. The number of times a certain package is downloaded is what we care about in terms of user breakdown rather than the machine used to download it.

**Comment by fedorov** [comment]
Interesting. I would expect that download per OS would be correlated with the website sessions per OS, but I can't figure out how or if it is possible at all to get the breakdown of per-OS sessions over time in Google Analytics. It is interesting that there seems to be a lot more sessions total on Mac than on Linux, but the stats for downloads do not reflect that.

![image](https://user-images.githubusercontent.com/313942/181630559-0022e818-c454-4341-a9ad-26e4fb08e08d.png)

**Comment by lassoan** [comment]
I don't have much experience with Google Analytics, but the difference that @jamesobutler found between the actual Slicer 5.0.x total downloads vs. after the filtering used by the download statistics is quite telling.

The filtering discarded 79% of the macOS downloads, while only 14% of linux downloads and 4% of Windows downloads.

**Comment by jamesobutler** [comment]
I think this is probably a case of the user agent information changing and messing up the Slicer download stats sniffing of that information while google analytics is getting the info correctly. The timeline matches various [User agent reduction](https://www.chromium.org/updates/ua-reduction/) activities to reduce passive fingerprinting on all the browsers and changes to the agent related to macOS 10.15 naming switching to macOS 11 resulting in capping of the agent version.

**Comment by jcfr** [comment]
This makes sense. To address this, plan is to:
* update the user-agent package to its latest version. See https://pypi.org/project/user-agents
* <s>rely on the platform associated with the downloaded package to identify the platform + rely on the user agent to check the download attempt should be discarded  (bot/crawler vs legitimate download)</s>

**Comment by lassoan** [comment]
@jcfr Have you had time to look at this? It would be important to know if there is a real drop or just a bug in the statistics computation.

**Comment by lassoan** [comment]
The issue still persists:

![image](https://user-images.githubusercontent.com/307929/196448800-a5aebc9d-293d-43fe-9d63-fdaebf7d664b.png)

**Comment by mhalle** [comment]
Perhaps MacOS has new privacy features that are preventing browser fingerprinting? That’s what I would bet on.

—Mike

**Comment by jcfr** [comment]
After implementing the following changes:
* update of `ua-parser` from `0.10.0` to `0.16.1`
* update of the logic building the `access` table to also include `MobileBrowser`. See [etc/slicer_parselogs/slicerstats.py#L41](https://github.com/Slicer/slicer_download/blob/cf11d919c6881de8193c5e976986eda9399e160e/etc/slicer_parselogs/slicerstats.py#L41)


The stats seems to include the missing macOS downloads:

| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/196755004-85f50814-ad5d-435f-8549-5fa3af74de92.png) | ![image](https://user-images.githubusercontent.com/219043/196755058-c0c9a8f1-0953-4b9d-b110-fe0c47757f26.png) |
| ![image](https://user-images.githubusercontent.com/219043/196755158-249d0b3c-0ff3-4fc6-8ed2-08e73bdf34d6.png) | ![image](https://user-images.githubusercontent.com/219043/196755244-8d6af438-ce4f-45a3-8cd3-e40d73cf0a75.png) |

**Comment by jcfr** [comment]
Additional comparison based on data from 2022.10.19:


| | Before | After | Difference |
|--|--|--|--|
| All | `1,132,388` | `1,180,023`| `+47,635` |
| Linux | `138,881`  | `141,521` | `+2,640` |
| macOS | `184,779` | `219,565` | `+34,786` |
| Windows | `808,728` | `818,937` | `+10,209` |

**Comment by lassoan** [comment]
Awesome, thanks for the update. It is great that it is confirmed to be a data collection issue and not an actual dropout of users.

We can close the issue when the production server is updated with the fixes.

**Comment by jamesobutler** [comment]
@jcfr Is the production server going to be updated soon? I still see at https://download.slicer.org/download-stats/ that macOS downloads are still down.

**Comment by lassoan** [comment]
@jcfr The fix was ready one year ago but it seems that the production server is still not updated. Is there anything we could help to get the download reporting fixed?

macOS download stats are kind of meaningless now:

![image](https://github.com/Slicer/slicer_download_stats/assets/307929/afa3ec71-b0a8-4891-ac98-9e7bfe143b1e)

**Comment by jcfr** [comment]
I was planning to address this today so that stats are relevant before RSNA.

**Comment by lassoan** [comment]
Awesome, thank you! What a coincidence...
